---
- hosts: localhost #172.19.110.8
  become: yes
  become_user: root
  become_method: sudo
    # community.general.docker_install:
    #   state: present

  tasks:
    - name: Install the docker Python package
      pip:
        name: docker

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker's official apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

          #    - name: Update the apt package index
          #apt:
          #update_cache: yes

    - name: Install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Build Docker image
      community.docker.docker_image:
        source: build
        build:
          path: "/home/devops/webapp" # Update this path to the directory containing your Dockerfile
        name: "ansible-docker-image7"
        tag: "latest" # You can specify a tag here if needed

